name: Automated project testing
on:
  push:
    paths:
      - 'data/**'
      - 'project/**'


      on:
        push:
          paths:
            - 'data/**'
            - 'project/**'
      
      jobs:
        test:
          runs-on: ubuntu-latest
      
          steps:
            - name: Checkout repository
              uses: actions/checkout@v2
      
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.x
      
            - name: Change directory to project
              run: cd project
      
            - name: Set execute permissions for tests.sh
              run: chmod +x tests.sh
      
            - name: Run tests
              run: ./tests.sh