name: Automated project testing
on:
  push:
    branches:
      - main
    paths:
      -  project/**
      -  data/**
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run tests.sh
        working-directory: ./project
        run: |
          chmod +x tests.sh
          tests.sh