name: Automated project testing
on:
  push:
    paths:
      - 'data/**'
      - 'project/**'


jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run tests
        run: |
          cd project
          chmod +x tests.sh
          bash tests.sh